Repository Schrodinger-AI/orlean-image-generator, pull requests merged in 2024-03, with the labels that each got.

#4 child grain timer
  Grains/dalle-image-generator/ImageGeneratorGrain.cs
  Grains/dalle-image-generator/MultiImageGeneratorGrain.cs
  Grains/interfaces/ImageGenerationGrainInterface.cs
  Shared/ImageGenerationGrainsResponse.cs
Labels: enhancement

#8 feat: Notify ParentGrain
  Grains/dalle-image-generator/ImageGeneratorGrain.cs
  Grains/dalle-image-generator/MultiImageGeneratorGrain.cs
  Grains/dalle-image-generator/MultiImageGeneratorState.cs
  Grains/interfaces/ImageGenerationGrainInterface.cs
Labels: enhancement

#22 fix: ImageGeneration trigger fix
  Grains/dalle-image-generator/ImageGeneratorGrain.cs
  Grains/dalle-image-generator/ImageGeneratorState.cs
  Grains/dalle-image-generator/MultiImageGeneratorGrain.cs
Labels: enhancement

#27 Image Generator Enhancements
  Grains/dalle-image-generator/ImageGeneratorGrain.cs
  Shared/ImageGenerationAPISchema.cs
  WebApiClient/controllers/MultiImageGeneratorController.cs
Labels: enhancement

#30 feat: set prompt in extraData
  Grains/dalle-image-generator/ImageGeneratorGrain.cs
  Shared/ImageGenerationAPISchema.cs
Labels: enhancement

#31 fix: set image-not-ready as return response when image-generation fails or in-progress
  WebApiClient/controllers/MultiImageGeneratorController.cs
Labels: enhancement

#46 feat: Seri Log with Rotation
  .gitignore
  Grains/Grains.csproj
  Grains/dalle-image-generator/ImageGeneratorGrain.cs
  Grains/dalle-image-generator/MultiImageGeneratorGrain.cs
  SiloHost/Program.cs
  SiloHost/SiloHost.csproj
  WebApiClient/Program.cs
  WebApiClient/Startup.cs
  WebApiClient/controllers/MultiImageGeneratorController.cs
  WebApiClient/controllers/SchedulerController.cs
Labels: enhancement

#51 fix: update the siloPort config in appsettings
  SiloHost/appsettings.json
Labels: enhancement

#56 feat: dalle error codes
  Grains/dalle-image-generator/ImageGeneratorGrain.cs
  Grains/dalle-image-generator/MultiImageGeneratorGrain.cs
  Grains/interfaces/DalleAPISchema.cs
  Grains/usage-tracker/SchedulerGrain.cs
  Shared/DalleException.cs
  Shared/ImageGenerationConstants.cs
  Shared/ImageGenerationGrainsResponse.cs
Labels: enhancement

#63 fix: add logs for image-query on controller
  Grains/dalle-image-generator/MultiImageGeneratorGrain.cs
  WebApiClient/controllers/MultiImageGeneratorController.cs
Labels: bug

#64 fix: add logging to MultiImageGeneratorController
  WebApiClient/controllers/MultiImageGeneratorController.cs
Labels: bug

#65 fix: view function to get the current status of imageGeneration
  Grains/dalle-image-generator/MultiImageGeneratorGrain.cs
  WebApiClient/controllers/MultiImageGeneratorController.cs
Labels: bug

#68 doc: ImageGeneration Status transition documentation
  docs/image-generation-status-transition.MD
  docs/image-generator-grain-status-transition.png
  readme.MD
Labels: documentation

#62 feat: content_policy_violation dalle error handling
  Grains/dalle-image-generator/ImageGeneratorGrain.cs
  Grains/usage-tracker/IImageGenerationRequestStatusReceiver.cs
  Grains/usage-tracker/SchedulerGrain.cs
  Shared/ImageGenerationConstants.cs
Labels: enhancement

#66 Feature/blocking list
  Grains/Grains.csproj
  Grains/ObserverManager.cs
  Grains/dalle-image-generator/ImageGeneratorGrain.cs
  Grains/dalle-image-generator/ImageGeneratorState.cs
  Grains/dalle-image-generator/MultiImageGeneratorState.cs
  Grains/dalle-prompt-creator/PrompterState.cs
  Grains/types/APIAccountInfo.cs
  Grains/types/BlockedRequestInfo.cs
  Grains/types/RequestAccountUsageInfo.cs
  Grains/types/RequestStatus.cs
  Grains/usage-tracker/ISchedulerGrain.cs
  Grains/usage-tracker/SchedulerGrain.cs
  Grains/usage-tracker/SchedulerState.cs
  Shared/ApiKeyEntry.cs
  Shared/ApiKeyUsageInfo.cs
  Shared/ImageGenerationAPISchema.cs
  Shared/ImageGenerationGrainsResponse.cs
  Shared/PrompterConfig.cs
  Shared/SchedulerAPISchema.cs
  Shared/Shared.csproj
  Shared/TraitConfigAPISchema.cs
  Shared/TraitEntry.cs
  SiloHost/Program.cs
  SiloHost/SiloHost.csproj
  WebApiClient/Program.cs
  WebApiClient/Startup.cs
  WebApiClient/WebApiClient.csproj
  WebApiClient/controllers/SchedulerController.cs
  setup-guide/database/01-MySQL-Main.sql
  setup-guide/database/02-MySQL-Clustering.sql
  setup-guide/database/03-MySQL-Persistence.sql
  setup-guide/database/SQLServer-Clustering-3.7.0.sql
Labels: enhancement

#86 feat: update Prompt and traits
  Grains/dalle-image-generator/ImageGeneratorGrain.cs
  Grains/dalle-image-generator/MultiImageGeneratorGrain.cs
  Grains/interfaces/ImageGenerationGrainInterface.cs
  Shared/ImageGenerationAPISchema.cs
  WebApiClient/controllers/PromptUpdateController.cs
Labels: enhancement

#87 feat: content violation blocker
  Grains/dalle-image-generator/AzureOpenAI/AzureOpenAIImageGenerator.cs
  Grains/dalle-image-generator/DalleOpenAI/DalleOpenAIImageGenerator.cs
  Grains/dalle-image-generator/ImageGeneratorGrain.cs
  Grains/dalle-image-generator/ImageGeneratorState.cs
  Grains/dalle-image-generator/MultiImageGeneratorGrain.cs
  Grains/dalle-image-generator/MultiImageGeneratorState.cs
  Grains/interfaces/ImageGenerationGrainInterface.cs
  Shared/ImageGenerationAPISchema.cs
  Shared/ImageGenerationConstants.cs
  Shared/ImageGenerationGrainsResponse.cs
  WebApiClient/controllers/MultiImageGeneratorController.cs
Labels: enhancement

#94 feature: new endpoints and log
  Grains/dalle-image-generator/DalleOpenAI/DalleOpenAIImageGenerator.cs
  Grains/dalle-image-generator/MultiImageGeneratorGrain.cs
  Grains/interfaces/ImageGenerationGrainInterface.cs
  SiloHost/Program.cs
  WebApiClient/Program.cs
  WebApiClient/controllers/MultiImageGeneratorController.cs
Labels: enhancement
